# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 773)
        MainWindow.setStyleSheet("background-color: #111111;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 110, 424, 130))
        self.groupBox.setStyleSheet(".QGroupBox {\n"
"    border: 2px solid #fff;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 391, 31))
        self.label_2.setStyleSheet("font-style: normal;\n"
"font-weight: 800;\n"
"font-size: 24px;\n"
"color: #fff;")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 63px;\n"
"color: #00FB00;\n"
"font-style: normal;\n"
"font-weight: 800;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 330, 451, 241))
        self.groupBox_2.setStyleSheet(".QGroupBox {\n"
"    border: 2px solid #fff;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(30, 130, 361, 21))
        self.radioButton.setStyleSheet("font-weight: 800;\n"
"font-size: 20px;\n"
"color: #D9D9D9;")
        self.radioButton.setObjectName("radioButton")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 361, 61))
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("font-style: normal;\n"
"font-weight: 800;\n"
"font-size: 24px;\n"
"color: #fff;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 190, 401, 21))
        self.radioButton_2.setStyleSheet("font-weight: 800;\n"
"font-size: 20px;\n"
"color: #D9D9D9;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 230, 711, 431))
        self.groupBox_3.setStyleSheet(".QGroupBox{border: 2px solid #00FB00;}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.graphicsView = PlotWidget(self.groupBox_3)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 691, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.l_image = QtWidgets.QLabel(self.groupBox_3)
        self.l_image.setGeometry(QtCore.QRect(10, 10, 691, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_image.sizePolicy().hasHeightForWidth())
        self.l_image.setSizePolicy(sizePolicy)
        self.l_image.setText("")
        self.l_image.setPixmap(QtGui.QPixmap("11.jpg"))
        self.l_image.setScaledContents(True)
        self.l_image.setObjectName("l_image")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(720, 90, 311, 71))
        self.groupBox_4.setStyleSheet(".QGroupBox {\n"
"    border: 2px solid #00FB00;\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 271, 31))
        self.label_4.setStyleSheet("font-weight: 800;\n"
"font-size: 35px;\n"
"color: #00FB00;")
        self.label_4.setObjectName("label_4")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(950, 700, 181, 31))
        self.btn_download.setStyleSheet(".QPushButton{color: green;border: 1px solid white}")
        self.btn_download.setObjectName("btn_download")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Общее число моржей на фото"))
        self.label.setText(_translate("MainWindow", "2036"))
        self.radioButton.setText(_translate("MainWindow", "График распределения моржей"))
        self.label_3.setText(_translate("MainWindow", "Выберите что отразить на фото"))
        self.radioButton_2.setText(_translate("MainWindow", "Вывести каждого моржа отдельно"))
        self.label_4.setText(_translate("MainWindow", "Walrus Counter\n"
""))
        self.btn_download.setText(_translate("MainWindow", "Загрузить фото"))
from pyqtgraph import PlotWidget
