# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 767)
        MainWindow.setStyleSheet("background-color: #111111;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 424, 130))
        self.groupBox.setStyleSheet(".QGroupBox {\n"
"    border: 2px solid #fff;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 391, 31))
        self.label_2.setStyleSheet("font-style: normal;\n"
"font-weight: 800;\n"
"font-size: 24px;\n"
"color: #fff;")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size: 63px;\n"
"color: #00FB00;\n"
"font-style: normal;\n"
"font-weight: 800;")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(500, 260, 711, 431))
        self.groupBox_3.setStyleSheet(".QGroupBox{border: 2px solid #00FB00;}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.graphicsView = PlotWidget(self.groupBox_3)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 691, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.l_image = QtWidgets.QLabel(self.groupBox_3)
        self.l_image.setGeometry(QtCore.QRect(10, 10, 691, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_image.sizePolicy().hasHeightForWidth())
        self.l_image.setSizePolicy(sizePolicy)
        self.l_image.setText("")
        self.l_image.setPixmap(QtGui.QPixmap("../../../.designer/backup/11.jpg"))
        self.l_image.setScaledContents(True)
        self.l_image.setObjectName("l_image")
        self.btn_upload = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_upload.setGeometry(QtCore.QRect(0, 0, 711, 431))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.btn_upload.setFont(font)
        self.btn_upload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_upload.setStyleSheet(".QPushButton {\n"
"    border: 2px solid #fff;\n"
"    color: #fff;\n"
"    font-style: normal;\n"
"    font-weight: 800;\n"
"    font-size: 24px;\n"
"}\n"
".QPushButton:hover {\n"
"    border: 2px solid #00FB00;\n"
"    color: #00FB00;\n"
"}")
        self.btn_upload.setObjectName("btn_upload")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(270, 610, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.btn_download.setFont(font)
        self.btn_download.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_download.setStyleSheet(".QPushButton {\n"
"    font-style: normal;\n"
"    font-weight: 800;\n"
"    font-size: 18px;\n"
"    color: #fff;\n"
"    border: 1px solid #fff;\n"
"}\n"
".QPushButton:hover {\n"
"    border: 1px solid #00FB00;\n"
"    color: #00FB00;\n"
"}")
        self.btn_download.setCheckable(False)
        self.btn_download.setObjectName("btn_download")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 471, 321))
        self.groupBox_2.setStyleSheet(".QGroupBox {\n"
"    border: 2px solid #fff;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(40, 190, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.radioButton.setFont(font)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton.setStyleSheet(".QRadioButton {\n"
"    font-weight: 800;\n"
"    font-size: 20px;\n"
"    color: #D9D9D9;\n"
"}\n"
".QRadioButton:focus {\n"
"    color: #00FB00;\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("font-style: normal;\n"
"font-weight: 800;\n"
"font-size: 24px;\n"
"color: #fff;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 240, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_2.setStyleSheet(".QRadioButton {\n"
"    font-weight: 800;\n"
"    font-size: 20px;\n"
"    color: #D9D9D9;\n"
"}\n"
".QRadioButton:focus {\n"
"    color: #00FB00;\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 140, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(99)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radioButton_3.setStyleSheet(".QRadioButton {\n"
"    font-weight: 800;\n"
"    font-size: 20px;\n"
"    color: #D9D9D9;\n"
"}\n"
".QRadioButton:focus {\n"
"    color: #00FB00;\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.Nameprogramm = QtWidgets.QGroupBox(self.centralwidget)
        self.Nameprogramm.setGeometry(QtCore.QRect(890, 170, 311, 71))
        self.Nameprogramm.setStyleSheet(".QGroupBox {\n"
"    border: 2px solid #fff;\n"
"}")
        self.Nameprogramm.setTitle("")
        self.Nameprogramm.setObjectName("Nameprogramm")
        self.label_5 = QtWidgets.QLabel(self.Nameprogramm)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 281, 31))
        self.label_5.setStyleSheet("font-weight: 800;\n"
"font-size: 35px;\n"
"color: #00FB00;")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(4, 0, 1211, 761))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Downloads/Telegram Desktop/Back 2.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        self.btn_download.raise_()
        self.groupBox_2.raise_()
        self.Nameprogramm.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Общее число моржей на фото"))
        self.label.setText(_translate("MainWindow", "2036"))
        self.btn_upload.setText(_translate("MainWindow", "Кликните для загрузки фото"))
        self.btn_download.setText(_translate("MainWindow", "Скачать фото"))
        self.radioButton.setText(_translate("MainWindow", "График распределения моржей"))
        self.label_3.setText(_translate("MainWindow", "Выберите что отразить на фото"))
        self.radioButton_2.setText(_translate("MainWindow", "Отметить каждого моржа на фото"))
        self.radioButton_3.setText(_translate("MainWindow", "Изначальное фото"))
        self.label_5.setText(_translate("MainWindow", "Walrus Counter\n"
""))
from pyqtgraph import PlotWidget
